"use client";

import {
  ArrowLeftRight,
  AudioWaveform,
  Box,
  BrainCircuit,
  Bug,
  ChartNoAxesColumnIncreasing,
  CircleHelp,
  Clipboard,
  Compass,
  Copy,
  Eraser,
  Eye,
  FileDown,
  File,
  Folder,
  Image,
  FolderMinus,
  FolderPlus,
  FolderSymlink,
  Footprints,
  Gauge,
  GitBranch,
  GitFork,
  Globe,
  Hammer,
  History,
  Inbox,
  Keyboard,
  ListChecks,
  ListTodo,
  LogIn,
  LogOut,
  Map,
  Maximize2,
  MessageSquareText,
  Mic,
  Minimize2,
  Monitor,
  Newspaper,
  Package,
  Paperclip,
  PanelTop,
  PanelLeft,
  Pause,
  Pencil,
  Pin,
  Plug,
  Plus,
  Power,
  Puzzle,
  Radio,
  Redo2,
  Repeat2,
  Rocket,
  RotateCcw,
  ScrollText,
  Search,
  Server,
  Settings,
  Settings2,
  Share2,
  Shield,
  ShoppingCart,
  Sparkles,
  SquareTerminal,
  Stethoscope,
  Target,
  Terminal,
  Trash2,
  Users,
  Vibrate,
  Wrench,
  Zap,
  type LucideIcon,
} from "lucide-react";

const ICONS: Record<string, LucideIcon> = {
  paperclip: Paperclip,
  file: File,
  folder: Folder,
  image: Image,
  search: Search,
  layout: PanelLeft,
  edit: Pencil,
  chat: MessageSquareText,
  action: Terminal,
  advisor: Eye,
  agents: Users,
  branch: GitBranch,
  broadcast: Radio,
  bug: Bug,
  cart: ShoppingCart,
  clipboard: Clipboard,
  compass: Compass,
  compress: Minimize2,
  computer: Monitor,
  context: PanelTop,
  copy: Copy,
  eraser: Eraser,
  expand: Maximize2,
  export: FileDown,
  extension: Puzzle,
  eye: Eye,
  fast: Zap,
  folderMinus: FolderMinus,
  folderMove: FolderSymlink,
  folderPlus: FolderPlus,
  gauge: Gauge,
  gear: Settings2,
  globe: Globe,
  goal: Target,
  hammer: Hammer,
  handoff: ArrowLeftRight,
  history: History,
  host: Server,
  inbox: Inbox,
  jobs: ListTodo,
  keyboard: Keyboard,
  loop: Repeat2,
  mcp: Plug,
  memory: BrainCircuit,
  model: Box,
  news: Newspaper,
  package: Package,
  pause: Pause,
  pencil: Pencil,
  pin: Pin,
  plan: Map,
  plus: Plus,
  power: Power,
  prewalk: Footprints,
  prompt: MessageSquareText,
  question: CircleHelp,
  redo: Redo2,
  restart: RotateCcw,
  rocket: Rocket,
  rule: ScrollText,
  session: SquareTerminal,
  settings: Settings,
  share: Share2,
  shield: Shield,
  signIn: LogIn,
  signOut: LogOut,
  skill: Sparkles,
  stats: ChartNoAxesColumnIncreasing,
  stethoscope: Stethoscope,
  swap: ArrowLeftRight,
  todo: ListChecks,
  tools: Wrench,
  trash: Trash2,
  tree: GitFork,
  vibrate: Vibrate,
  voice: Mic,
  wave: AudioWaveform,
};

export function hasSlashCommandIcon(name: string): boolean {
  return name in ICONS;
}

export function SlashCommandIcon({ name }: { name?: string }) {
  const Icon = name ? ICONS[name] ?? Terminal : Terminal;
  return <Icon size={16} strokeWidth={1.5} aria-hidden="true" />;
}
