#!/usr/bin/env bash
#
# A wizard walks a human through a manual procedure, step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library: delightful, consistent UX, identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear wipes the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" shows the opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later, since it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" clears the screen, then announces a stage and shows progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." prints a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." is a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL opens it in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser; visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser, so visit it manually: $url"
}

# pause "msg" waits for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" is a y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY: current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" reads a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" is like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE upserts KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE sets a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name: gh not ready; set it later"
}

# set_var NAME VALUE sets a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name, gh not ready; set it later"
}

# finish clears, then shows a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES: Reeve release setup. Authored 2026-09-08 from ADR-0006 and tickets T7, T8, T9.
# ──────────────────────────────────────────────────────────────────────────

TOTAL_STAGES=7

# Human-only steps for Reeve 0.5.0: Apple signing secrets, the Ko-fi page,
# the switch to a public repository, and branch protection.
# Re-run at any time. Values already saved in .env.release are offered again.
# Every gh call below uses the AndrewBeniston account and the omp-reeve repo.

ENV_FILE=".env.release"
REEVE_REPO="AndrewBeniston/omp-reeve"
# Apple team IDs come from .env.release (APPLE_TEAM_ID) or the prompt below.
HELPSELF_TEAM="${APPLE_TEAM_ID:-}"
LOCAL_CERT_TEAM="${APPLE_LOCAL_TEAM_ID:-}"

if ! GH_TOKEN="$(gh auth token -u AndrewBeniston 2>/dev/null)" || [[ -z "$GH_TOKEN" ]]; then
  printf '  gh has no token for the AndrewBeniston account. Run: gh auth login\n' >&2
  exit 1
fi
export GH_TOKEN
export GH_REPO="$REEVE_REPO"

banner "Reeve release setup"

# ── Stage 1 ───────────────────────────────────────────────────────────────
stage "Apple: confirm the paid team"
say "Reeve must sign on the team that holds the paid Apple Developer Program."
say "electron-updater breaks if a later release is signed by a different team."
say "So this choice is permanent after 0.5.0."
open_url "https://developer.apple.com/account"
step "Sign in. Scroll to 'Membership details'."
step "Read the Team ID (ten characters) and the Program (must say Apple Developer Program)."
ask APPLE_TEAM_ID "Type the Team ID:"
case "$APPLE_TEAM_ID" in
  "$HELPSELF_TEAM")    note "That is the HelpSelf team. Expected.";;
  "$LOCAL_CERT_TEAM")  warn "That is the team of the certificate already on this Mac, not HelpSelf.";;
  *)                   warn "Unknown team. Check that it is the paid one.";;
esac
if ! confirm "Does the page say 'Apple Developer Program' with a paid membership for this team?"; then
  warn "Stop here. Enrol or renew at developer.apple.com/programs before you continue."
  exit 1
fi
write_env APPLE_TEAM_ID "$APPLE_TEAM_ID"

# ── Stage 2 ───────────────────────────────────────────────────────────────
stage "Apple: create the Developer ID Application certificate"
say "This certificate signs the macOS app for distribution outside the App Store."
say "Skip this stage if the team already has one and you hold its private key."
if confirm "Create a new Developer ID Application certificate now?"; then
  step "Open Keychain Access (Spotlight: Keychain Access)."
  step "Menu: Keychain Access > Certificate Assistant > Request a Certificate From a Certificate Authority."
  step "Email: your Apple ID email. Common Name: Andrew Beniston. CA Email: leave empty."
  step "Select 'Saved to disk'. Save CertificateSigningRequest.certSigningRequest to the Desktop."
  pause "Press Enter when the request file is saved."
  open_url "https://developer.apple.com/account/resources/certificates/add"
  note "Page labels below are from memory and may differ slightly."
  step "Under Software, select 'Developer ID Application'. Continue."
  step "If asked for a profile type, keep 'G2 Sub-CA (Xcode 11.4.1 or later)'."
  step "Upload the .certSigningRequest file. Continue. Download the .cer file."
  step "Double-click the downloaded .cer file. It installs into the login keychain."
  pause "Press Enter when the certificate is installed."
fi
if security find-identity -v -p codesigning 2>/dev/null | grep -q "Developer ID Application"; then
  note "Found on this Mac:"
  security find-identity -v -p codesigning | grep "Developer ID Application" | sed 's/^/    /'
else
  warn "No 'Developer ID Application' identity is in the keychain yet. Stage 3 will fail without it."
fi

# ── Stage 3 ───────────────────────────────────────────────────────────────
stage "Apple: export the certificate as .p12 for CI"
say "GitHub Actions needs the certificate and its private key as one .p12 file."
step "In Keychain Access, select the 'login' keychain and the 'My Certificates' category."
step "Find 'Developer ID Application: Andrew Beniston ($APPLE_TEAM_ID)'."
step "Right-click it. Choose 'Export ...'. Format: Personal Information Exchange (.p12)."
step "Save it as reeve-developer-id.p12 on the Desktop. Set a strong password when asked."
ask P12_PATH "Path to the .p12 file [Enter for ~/Desktop/reeve-developer-id.p12]:"
P12_PATH="${P12_PATH:-$HOME/Desktop/reeve-developer-id.p12}"
P12_PATH="${P12_PATH/#\~/$HOME}"
if [[ ! -f "$P12_PATH" ]]; then
  warn "File not found: $P12_PATH"
  exit 1
fi
ask_secret MACOS_CSC_KEY_PASSWORD "Type the .p12 password:"
MACOS_CSC_LINK="$(base64 < "$P12_PATH" | tr -d '\n')"
set_secret MACOS_CSC_LINK "$MACOS_CSC_LINK"
set_secret MACOS_CSC_KEY_PASSWORD "$MACOS_CSC_KEY_PASSWORD"
write_env P12_PATH "$P12_PATH"
note "The .p12 and its password are not written to .env.release."
note "Keep the file in a password manager, then delete it from the Desktop."

# ── Stage 4 ───────────────────────────────────────────────────────────────
stage "Apple: App Store Connect API key for notarization"
say "Notarization uploads each build to Apple. It authenticates with an API key."
open_url "https://appstoreconnect.apple.com/access/integrations/api"
note "Page labels below are from memory and may differ slightly."
step "Open the 'Team Keys' tab. Click the plus button."
step "Name: Reeve CI. Access: Developer. Generate."
step "Copy the Issuer ID shown at the top of the page."
ask APPLE_API_ISSUER "Paste the Issuer ID:"
step "Copy the Key ID of the new key."
ask APPLE_API_KEY_ID "Paste the Key ID:"
step "Click 'Download API Key'. Apple allows one download only. Keep the file in Downloads."
ask P8_PATH "Path to the .p8 file [Enter for ~/Downloads/AuthKey_$APPLE_API_KEY_ID.p8]:"
P8_PATH="${P8_PATH:-$HOME/Downloads/AuthKey_$APPLE_API_KEY_ID.p8}"
P8_PATH="${P8_PATH/#\~/$HOME}"
if [[ ! -f "$P8_PATH" ]]; then
  warn "File not found: $P8_PATH"
  exit 1
fi
set_secret APPLE_API_KEY "$(cat "$P8_PATH")"
set_secret APPLE_API_KEY_ID "$APPLE_API_KEY_ID"
set_secret APPLE_API_ISSUER "$APPLE_API_ISSUER"
write_env APPLE_API_KEY_ID "$APPLE_API_KEY_ID"
write_env APPLE_API_ISSUER "$APPLE_API_ISSUER"
write_env P8_PATH "$P8_PATH"
note "Store the .p8 in a password manager. Apple will not let you download it again."

# ── Stage 5 ───────────────────────────────────────────────────────────────
stage "Ko-fi: create the support page"
say "Ko-fi takes 0% of tips. The page name goes into the README, the app, and FUNDING.yml."
open_url "https://ko-fi.com/"
step "Sign up. Choose a page name, for example 'reeve' or 'andrewbeniston'."
step "Set a display name and a short line about Reeve. Connect PayPal or Stripe for payouts."
ask KOFI_NAME "Type the Ko-fi page name (the part after ko-fi.com/):"
KOFI_NAME="${KOFI_NAME#https://ko-fi.com/}"
KOFI_NAME="${KOFI_NAME#ko-fi.com/}"
write_env KOFI_NAME "$KOFI_NAME"
mkdir -p .github
printf 'ko_fi: %s\n' "$KOFI_NAME" > .github/FUNDING.yml
printf '  %s✓ wrote%s .github/FUNDING.yml\n' "$GREEN" "$RESET"

# ── Stage 6 ───────────────────────────────────────────────────────────────
stage "GitHub: make the repository public"
say "Run this stage only after ticket T1 (hygiene) and the T9 squash have landed on main."
say "The squash removes the Codex reference CSS, inbox/, and personal paths."
current_visibility="$(gh repo view "$REEVE_REPO" --json visibility --jq .visibility 2>/dev/null || echo unknown)"
note "Current visibility: $current_visibility"
if [[ "$current_visibility" == "PUBLIC" ]]; then
  note "Already public. Nothing to do."
elif confirm "Has the clean squash commit landed on main, with T1 complete?"; then
  if confirm "Make $REEVE_REPO public now? This is hard to reverse."; then
    if gh repo edit "$REEVE_REPO" --visibility public --accept-visibility-change-consequences; then
      printf '  %s✓ repository is public%s\n' "$GREEN" "$RESET"
    else
      SKIPPED+=("make repository public (gh repo edit failed)")
      warn "gh repo edit failed. Do it in Settings > Danger Zone instead."
    fi
  fi
else
  SKIPPED+=("make repository public (after T1 and the squash)")
  note "Skipped. Re-run this wizard after the squash."
fi

# ── Stage 7 ───────────────────────────────────────────────────────────────
stage "GitHub: protect main"
say "Every change lands through a pull request with green CI. No direct push."
if confirm "Apply branch protection to main now?"; then
  protection='{"required_status_checks":{"strict":true,"contexts":[]},"enforce_admins":false,"required_pull_request_reviews":{"required_approving_review_count":0},"restrictions":null,"allow_force_pushes":false,"allow_deletions":false,"required_linear_history":true}'
  if printf '%s' "$protection" | gh api -X PUT "repos/$REEVE_REPO/branches/main/protection" --input - >/dev/null; then
    printf '  %s✓ main is protected%s\n' "$GREEN" "$RESET"
    note "Add the CI job names to required status checks after the first public CI run reports."
  else
    SKIPPED+=("branch protection on main (gh api failed)")
    warn "gh api failed. Set it in Settings > Branches instead."
  fi
else
  SKIPPED+=("branch protection on main")
fi

finish
